# standalone-server-configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost # set hostname of all services to 'localhost'

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh

---
# high-availability-configuration
spring:
  config:
    activate:
      on-profile: ha
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka