# standalone-server-configuration
server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false

---
# high-availability-configuration
spring:
  config:
    activate:
      on-profile: ha

eureka:
  client:
    service-url:
      defaultZone: http://${other.eureka.hostname}:${other.eureka.port}/eureka
    fetch-registry: true
    register-with-eureka: true

---
spring:
  config:
    activate:
      on-profile: eureka-1
  application:
    name: eureka-1

server:
  port: 8761

other:
  eureka:
    hostname: localhost
    port: 8762

---
spring:
  config:
    activate:
      on-profile: eureka-2
  application:
    name: eureka-2

server:
  port: 8762

other:
  eureka:
    hostname: localhost
    port: 8761